# Generated by Django 4.1.5 on 2023-03-05 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_name', models.CharField(default='Feedback Form', max_length=100)),
                ('company_name', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
                ('completion_rate', models.IntegerField()),
                ('self_review', models.JSONField(blank=True)),
                ('peer_review', models.JSONField(blank=True)),
                ('manager_review', models.JSONField(blank=True)),
                ('direct_report_review', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('doj', models.DateField(null=True)),
                ('cohesieve_role', models.CharField(max_length=50)),
                ('cohesieve_user_id', models.IntegerField()),
                ('cohesieve_user_name', models.CharField(max_length=50)),
                ('cohesieve_workspace_id', models.IntegerField()),
                ('cohesieve_workspace_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_2', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.feedbackform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='people',
            field=models.ManyToManyField(related_name='people', to='Main.userprofile'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_for', models.CharField(max_length=50)),
                ('feedback_type', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('questions_answers', models.JSONField()),
                ('form_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.feedbackform')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Main.userprofile')),
            ],
        ),
    ]
