# Generated by Django 4.1.5 on 2023-03-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_userprofile_company_name_alter_feedback_user_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='form_id',
            field=models.IntegerField(),
        ),
    ]
