# Generated by Django 4.1.5 on 2023-03-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_userprofile_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
