# Generated by Django 4.1.5 on 2023-03-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_feedback_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cohesieve_role',
            new_name='cohesive_role',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='cohesieve_user_id',
            new_name='cohesive_user_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='cohesieve_user_name',
            new_name='cohesive_user_name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='cohesieve_workspace_id',
            new_name='cohesive_workspace_id',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='cohesieve_workspace_name',
            new_name='cohesive_workspace_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
            preserve_default=False,
        ),
    ]
