# Generated by Django 4.1.5 on 2023-03-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Main", "0006_rename_cohesieve_role_userprofile_cohesive_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="form_name",
            field=models.CharField(default="Form", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="feedbackstatus",
            name="form_name",
            field=models.CharField(default="Form", max_length=50),
            preserve_default=False,
        ),
    ]
